register:
    description: Start tracking a package
    fields:
        package_id:
            description: The id of the package to track.
            example: "123456789"

unregister:
    description: Stop tracking a package
    fields:
        package_id:
            description: The id of the package to stop to track.
            example: "123456789"
